function sys=SpeedgoatCANOpen07ref
sys = [];
sys.child = [];
sys.NumDataTypes = 9; 
sys.DataTypes = [];
temp.EnumNames='';
temp.EnumValues = [];
temp.Name = '';
sys.DataTypes = repmat(temp,1,9);
sys.DataTypes(1).Name = 'uint16_T';
sys.DataTypes(2).Name = 'uint8_T';
sys.DataTypes(3).Name = 'int16_T';
sys.DataTypes(4).Name = 'int8_T';
sys.DataTypes(5).Name = 'int32_T';
sys.DataTypes(6).Name = 'real32_T';
sys.DataTypes(7).Name = 'real_T';
sys.DataTypes(8).Name = 'uint32_T';
sys.DataTypes(9).Name = 'boolean_T';
